# -*- coding: utf-8 -*-
"""run_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4fr80m2mlTVar5stJE5LbuTuXiSSZ3j
"""

import subprocess
import sys
import hopsworks

def run_script(script_name):
    print(f"\n➡️ Running {script_name} ...")
    result = subprocess.run([sys.executable, script_name], capture_output=True, text=True)

    if result.returncode != 0:
        print(f"❌ Error in {script_name}:\n{result.stderr}")
        sys.exit(result.returncode)
    else:
        print(f"✅ {script_name} completed!")

def upload_model_to_hopsworks(model_path, scaler_path):
    print("\n➡️ Logging in to HopsWorks...")
    project = hopsworks.login()
    mr = project.get_model_registry()

    # Upload model
    rf_model_entity = mr.python.create_model(
        name="rf_aqi_model",
        metrics={},
        description="Random Forest model for AQI prediction"
    )
    rf_model_entity.save(model_path)
    print("✅ Model uploaded!")

    # Upload scaler
    scaler_entity = mr.python.create_model(
        name="scaler_aqi",
        metrics={},
        description="Scaler for AQI prediction"
    )
    scaler_entity.save(scaler_path)
    print("✅ Scaler uploaded!")

if __name__ == "__main__":
    run_script("fetch_data.py")
    run_script("preprocess.py")
    run_script("train_model.py")
    upload_model_to_hopsworks("best_model.pkl", "scaler.pkl")
    run_script("predict_aqi.py")

    print("\n🎉 Pipeline completed successfully!")